################################################################################
MLI_FILE		= cordova_splashscreen.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-splashscreen
################################################################################
